version: 2
jobs:
  "node-14":
    docker:
      - image: circleci/node:14
    working_directory: ~/daylight
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run report
      - store_test_results:
          path: ~/daylight/reports
  "node-13":
    docker:
      - image: circleci/node:13
    working_directory: ~/daylight
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run report
      - store_test_results:
          path: ~/daylight/reports
  "node-12":
    docker:
      - image: circleci/node:12
    working_directory: ~/daylight
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run report
      - store_test_results:
          path: ~/daylight/reports
  "node-10":
    docker:
      - image: circleci/node:10
    working_directory: ~/daylight
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run report
      - store_test_results:
          path: ~/daylight/reports
  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/daylight
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run report
      - store_test_results:
          path: ~/daylight/reports

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - "master"
    jobs:
      - "node-14"
  build:
    jobs:
      - "node-14"
      - "node-13"
      - "node-12"
      - "node-10"
      - "node-8"
